# Generated by Django 6.0.1 on 2026-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastsubmission',
            name='submission_type',
            field=models.CharField(choices=[('auto', 'Auto-detected'), ('code', 'Code Screenshot'), ('room', 'Living Room Photo'), ('resume', 'Resume'), ('other', 'Other')], default='auto', max_length=20),
        ),
    ]
